version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-23.2-alpine}'
    container_name: 'clickhouse-js-clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - './.docker/clickhouse/single_node/config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml'

  clickhouse_tls:
    build:
      context: ./
      dockerfile: .docker/clickhouse/single_node_tls/Dockerfile
    container_name: 'clickhouse-js-clickhouse-server-tls'
    ports:
      - '8443:8443'
      - '9440:9440'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - './.docker/clickhouse/single_node_tls/config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse/single_node_tls/users.xml:/etc/clickhouse-server/users.xml'
