name: 'run tests'

on:
  push:
    branches:
      - main
  pull_request:
#    branches:
#      - main
  schedule:
    - cron: '0 9 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [14, 16]
        clickhouse: [head, latest]

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:${{ matrix.clickhouse }}
        ports:
          - 8123:8123
          - 9000:9000
        options: --ulimit nofile=262144:262144

    steps:
      - uses: actions/checkout@main

      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run linting
        run: |
          npm run lint

      - name: Compile
        run: |
          npm run compile

      - name: Run tests
        env:
          CLICKHOUSE_CLOUD_HOST: ${{ secrets.CLICKHOUSE_CLOUD_HOST }}
          CLICKHOUSE_CLOUD_USERNAME: ${{ secrets.CLICKHOUSE_CLOUD_USERNAME }}
          CLICKHOUSE_CLOUD_PASSWORD: ${{ secrets.CLICKHOUSE_CLOUD_PASSWORD }}
          CLICKHOUSE_CLOUD_ENABLED: 'true'
        run: |
          npm test
