name: "bun"

permissions: {}
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
    paths:
      - "packages/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.base.json"
      - "tsconfig.dev.json"
      - "eslint.config.base.mjs"
      - "docker-compose.yml"
      - "vitest.node.config.ts"
      - "vitest.node.setup.ts"
      - "vitest.web.config.ts"
      - "vitest.web.setup.ts"
      - ".github/workflows/tests-bun.yml"
  pull_request:
    paths:
      - "packages/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.base.json"
      - "tsconfig.dev.json"
      - "eslint.config.base.mjs"
      - "docker-compose.yml"
      - "vitest.node.config.ts"
      - "vitest.node.setup.ts"
      - "vitest.web.config.ts"
      - "vitest.web.setup.ts"
      - ".github/workflows/tests-bun.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  common-unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: |
          bun install

      - name: Run common unit tests
        run: |
          npm run test:common:unit:bun

  node-unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: |
          bun install

      - name: Run node unit tests
        run: |
          npm run test:node:unit:bun
